#!/usr/bin/env python3
# Classifarr Image Embedding Service - companion service for Classifarr
# Copyright (C) 2024-2026 Classifarr Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

"""
First-time setup: generate .env (secrets) and config.toml (settings).

Usage:
    python scripts/generate_env.py

- Creates .env with a cryptographically random SERVICE_API_KEY.
- Creates config.toml with default application settings (if not already present).
- Neither file will be overwritten without --force.
"""

import argparse
import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
ENV_FILE = ROOT / ".env"
CONFIG_FILE = ROOT / "config.toml"

ENV_TEMPLATE = """\
# Classifarr Image Embedding Service — secrets
# Generated by scripts/generate_env.py — DO NOT COMMIT THIS FILE
#
# Non-secret settings (model, queue, auth modes, rate limits) live in config.toml.

# Shared API key between this service and Classifarr.
# Copy this value into Classifarr Settings -> API Keys (embed_service tier).
SERVICE_API_KEY={api_key}
"""

CONFIG_TEMPLATE = """\
# Classifarr Image Embedding Service — application configuration
# This file is mounted read-only into the container (mode 0444 via Docker configs).
# Environment variables always override values defined here — useful for CI overrides.
# Secrets (SERVICE_API_KEY) must never appear in this file — use .env instead.

[server]
host = "0.0.0.0"
port = 8000
shutdown_timeout_seconds = 30

[model]
default_model = "ViT-L-14"
device = "auto"             # "auto" selects cuda if available, else cpu
warmup_on_startup = true

[image]
allow_remote_urls = false
allowed_remote_hosts = []   # when allow_remote_urls = true, restrict to these hosts
max_image_bytes = 10485760  # 10 MiB
request_timeout_seconds = 15

[queue]
concurrency = 1
max_queue = 100
max_wait_seconds = 60

[logging]
level = "INFO"              # DEBUG, INFO, WARNING, ERROR
json_format = false
max_bytes = 10485760        # 10 MiB per log file before rotation
backup_count = 5

[memory]
cleanup_interval_seconds = 300
max_process_memory_mb = 0   # 0 = no limit
max_gpu_memory_mb = 0       # 0 = no limit
cleanup_on_shutdown = true

[auth]
require_api_key = true
rate_limit_embed = "30/minute"  # format: "<count>/<period>" e.g. "10/minute", "2/second"
# SERVICE_API_KEY is intentionally absent — set it via the .env file (see scripts/generate_env.py)
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Set up .env and config.toml for the embedding service.")
    parser.add_argument("--force", action="store_true", help="Overwrite existing files.")
    args = parser.parse_args()

    if ENV_FILE.exists() and not args.force:
        print(f"✖  {ENV_FILE} already exists. Use --force to regenerate.")
        sys.exit(1)

    api_key = secrets.token_urlsafe(32)
    ENV_FILE.write_text(ENV_TEMPLATE.format(api_key=api_key), encoding="utf-8")
    print(f"✔  Generated {ENV_FILE}")

    if not CONFIG_FILE.exists():
        CONFIG_FILE.write_text(CONFIG_TEMPLATE, encoding="utf-8")
        print(f"✔  Generated {CONFIG_FILE} (default settings — edit to customise)")
    else:
        print(f"   {CONFIG_FILE} already exists — not overwritten")

    print()
    print(f"   SERVICE_API_KEY = {api_key}")
    print()
    print("   Next steps:")
    print("   1. Copy the SERVICE_API_KEY value above.")
    print("   2. In Classifarr: Settings → API Keys → create a key with the 'embed_service' tier.")
    print("      Paste this value there, or set IMAGE_EMBEDDER_API_KEY in Classifarr's environment.")
    print("   3. (Optional) Edit config.toml to adjust model, rate limits, etc.")
    print("   4. Run: docker compose up -d")


if __name__ == "__main__":
    main()
