#!/usr/bin/env python3
# Classifarr Image Embedding Service - companion service for Classifarr
# Copyright (C) 2024-2026 Classifarr Contributors
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Generate a .env file with a secure random SERVICE_API_KEY.

Usage:
    python scripts/generate_env.py

Will not overwrite an existing .env file. Run with --force to regenerate.
"""

import argparse
import secrets
import sys
from pathlib import Path

ENV_FILE = Path(__file__).parent.parent / ".env"

TEMPLATE = """\
# Classifarr Image Embedding Service — secrets
# Generated by scripts/generate_env.py — DO NOT COMMIT THIS FILE
#
# Non-secret settings (model, queue, auth modes, rate limits) live in config.toml.

# Shared API key between this service and Classifarr.
# Copy this value into Classifarr Settings -> API Keys (embed_service tier).
SERVICE_API_KEY={api_key}
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate .env for the embedding service.")
    parser.add_argument("--force", action="store_true", help="Overwrite existing .env file.")
    args = parser.parse_args()

    if ENV_FILE.exists() and not args.force:
        print(f"✖  {ENV_FILE} already exists. Use --force to regenerate.")
        sys.exit(1)

    api_key = secrets.token_urlsafe(32)
    ENV_FILE.write_text(TEMPLATE.format(api_key=api_key), encoding="utf-8")

    print(f"✔  Generated {ENV_FILE}")
    print()
    print(f"   SERVICE_API_KEY = {api_key}")
    print()
    print("   Next steps:")
    print("   1. Copy the SERVICE_API_KEY value above.")
    print("   2. In Classifarr: Settings → API Keys → create a key with the 'embed_service' tier.")
    print("      Paste this value there, or set IMAGE_EMBEDDER_API_KEY in Classifarr's environment.")
    print("   3. Run: docker compose up -d")


if __name__ == "__main__":
    main()
